basePath: /
definitions:
  models.Product:
    properties:
      harga:
        type: number
      id:
        type: integer
      nama_produk:
        type: string
    type: object
  models.User:
    properties:
      email:
        type: string
      id:
        type: integer
      nama:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Membuat API CRUD dengan menggunakan bahasa GO
  title: UAS - Pemrograman Berbasis Platform
  version: "1.0"
paths:
  /api/login:
    post:
      consumes:
      - application/json
      description: Autentikasi user
      parameters:
      - description: Kredensial login user
        in: body
        name: loginUser
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Login user
  /api/products/:
    get:
      description: Get a list of all products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
      summary: Get all products
    post:
      consumes:
      - application/json
      description: Create a new product with the provided details
      parameters:
      - description: Product object to be created
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Product'
      summary: Create a new product
  /api/products/{id}:
    delete:
      description: Delete a product by its ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Delete a product by ID
    put:
      consumes:
      - application/json
      description: Update a product with the provided details
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product object to be updated
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
      summary: Update a product by ID
  /api/users/:
    get:
      description: Mengambil daftar semua user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
      summary: Mengambil semua user
    post:
      consumes:
      - application/json
      description: Membuat user baru dengan detail yang diberikan
      parameters:
      - description: Objek user yang akan dibuat
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
      summary: Membuat user baru
  /api/users/{id}:
    delete:
      description: Menghapus user berdasarkan ID mereka
      parameters:
      - description: ID user
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Menghapus user berdasarkan ID
    put:
      consumes:
      - application/json
      description: Memperbarui user dengan detail yang diberikan
      parameters:
      - description: ID user
        in: path
        name: id
        required: true
        type: integer
      - description: Objek user yang akan diperbarui
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Memperbarui user berdasarkan ID
schemes:
- http
- https
swagger: "2.0"
